image: node:10.15.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
