language: node_js
node_js: stable # 设置相应版本
# Specify which branches to build using a safelist
# 分支白名单限制: 只有master分支的提交才会触发构建
branches:
  only:
    - master

# install:
install:
    - npm install

script:
# 运行命令
  - npm run build

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  target-branch: travis-pages # 要将静态站点文件发布到哪个分支
  github-token: $GH_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  #fqdn: blog.yuantops.com # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支